ydb:
  # DB endpoint host:port to connect to
  endpoint: ydb-vla-testing-0000.search.yandex.net:2135 

  # Database path
  database: /kqp_dev_vla/asmyasnikov 

  # Folder to store data in
  folder: jaeger-k8s-prod

  useMetaAuth: false

  env:
    YDB_TOKEN: ""

image:
  query:
    pullPolicy: IfNotPresent
    repository: kind/jaeger-ydb-query
    tag: v1.9.0
  collector:
    pullPolicy: IfNotPresent
    repository: kind/jaeger-ydb-collector
    tag: v1.9.0
  watcher:
    pullPolicy: IfNotPresent
    repository: kind/jaeger-ydb-watcher
    tag: v1.9.0
  agent:
    pullPolicy: IfNotPresent
    repository: jaegertracing/jaeger-agent
    tag: 1.27

collector:
  enabled: true
  replicas: 3
  affinity: {}
  nodeSelector: {}
  tolerations: []
  securityContext: {}
  podSecurityContext: {}
  podAnnotations: {}

query:
  enabled: true
  replicas: 3
  affinity: {}
  nodeSelector: {}
  tolerations: []
  securityContext: {}
  podSecurityContext: {}
  podAnnotations: {}

watcher:
  enabled: true
  replicas: 2
  affinity: {}
  nodeSelector: {}
  tolerations: []
  securityContext: {}
  podSecurityContext: {}
  podAnnotations: {}

agent:
  enabled: true
  podSecurityContext: {}
  securityContext: {}
  annotations: {}
  pullPolicy: IfNotPresent
  cmdlineParams: {}
  extraEnv: []
  daemonset:
    useHostPort: false
    updateStrategy: {}
      # type: RollingUpdate
      # rollingUpdate:
      #   maxUnavailable: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  extraSecretMounts: []
  # - name: jaeger-tls
  #   mountPath: /tls
  #   subPath: ""
  #   secretName: jaeger-tls
  #   readOnly: true
  extraConfigmapMounts: []
  # - name: jaeger-config
  #   mountPath: /config
  #   subPath: ""
  #   configMap: jaeger-config
  #   readOnly: true
  useHostNetwork: false
  dnsPolicy: ClusterFirst
  priorityClassName: ""


service:
  collector:
    type: ClusterIP
    # headless: false
    # ipFamilies:
    #   - IPv6
    #   - IPv4
    # ipFamilyPolicy: PreferDualStack
    annotations: {}
    ports:
      grpc:
        name: grpc
        port: 14250
        # nodePort: 34250
      http:
        name: http
        port: 14268
  query:
    type: LoadBalancer
    annotations: {}
    ports:
      http:
        name: http
        port: 16686
  agent:
    type: ClusterIP
    annotations: {}
    ports:
      zipkin-compact:
        # Accept zipkin.thrift over compact thrift protocol
        name: zipkin-compact
        port: 5775
        protocol: UDP
      jaeger-compact:
        # Accept jaeger.thrift over compact thrift protocol
        name: jaeger-compact
        port: 6831
        protocol: UDP
      jaeger-binary:
        # Accept jaeger.thrift over binary thrift protocol
        name: jaeger-binary
        port: 6832
        protocol: UDP
      http:
        # (HTTP) serve configs, sampling strategies
        name: http
        port: 5778
        protocol: TCP

