{{- if .Values.agent.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "jaeger-ydb-store.fullname" . }}-agent
  labels:
    {{- include "jaeger-ydb-store.labels" . | nindent 4 }}
    {{- include "jaeger-ydb-store.agentSelectorLabels" $ | nindent 4 }}
{{- if .Values.agent.annotations }}
  annotations:
    {{- toYaml .Values.agent.annotations | nindent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      {{- include "jaeger-ydb-store.labels" . | nindent 6 }}
      {{- include "jaeger-ydb-store.agentSelectorLabels" $ | nindent 6 }}
  {{- with .Values.agent.daemonset.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- if .Values.agent.podAnnotations }}
      annotations:
        {{- toYaml .Values.agent.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jaeger-ydb-store.labels" . | nindent 8 }}
        {{- include "jaeger-ydb-store.agentSelectorLabels" $ | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.agent.podSecurityContext | nindent 8 }}
      {{- if .Values.agent.useHostNetwork }}
      hostNetwork: true
      {{- end }}
      dnsPolicy: {{ .Values.agent.dnsPolicy }}
      {{- with .Values.agent.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      serviceAccountName: {{ include "jaeger-ydb-store.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: agent
        securityContext:
          {{- toYaml .Values.agent.securityContext | nindent 10 }}
        image: "{{ .Values.image.agent.repository }}:{{ .Values.image.agent.tag }}"
        imagePullPolicy: {{ .Values.image.agent.pullPolicy }}
        args:
          {{- range $key, $value := .Values.agent.cmdlineParams }}
          {{- if $value }}
          - --{{ $key }}={{ $value }}
          {{- else }}
          - --{{ $key }}
          {{- end }}
          {{- end }}
        env:
        {{- if .Values.agent.extraEnv }}
          {{- toYaml .Values.agent.extraEnv | nindent 10 }}
        {{- end }}
        {{- if not (hasKey .Values.agent.cmdlineParams "reporter.grpc.host-port") }}
          - name: REPORTER_GRPC_HOST_PORT
            value: {{ include "jaeger-ydb-store.fullname" $ }}-collector:{{ .Values.service.collector.ports.grpc.port }}
        {{- end }}
        ports:
          - name: admin
            containerPort: 14271
            protocol: TCP
          {{- range $key, $value := merge dict .Values.service.agent.ports }}
          - name: {{ $key }}
            containerPort: {{ $value.port }}
            protocol: {{ default "TCP" $value.protocol }}
            {{- if $value.useHostPort }}
            hostPort: {{ $value.port }}
            {{- end }}
          {{- end }}
        livenessProbe:
          httpGet:
            path: /
            port: admin
        readinessProbe:
          httpGet:
            path: /
            port: admin
        resources:
          {{- toYaml .Values.resources.agent | nindent 10 }}
        volumeMounts:
        {{- range .Values.agent.extraConfigmapMounts }}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
            subPath: {{ .subPath }}
            readOnly: {{ .readOnly }}
        {{- end }}
        {{- range .Values.agent.extraSecretMounts }}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
            subPath: {{ .subPath }}
            readOnly: {{ .readOnly }}
        {{- end }}
      volumes:
      {{- range .Values.agent.extraConfigmapMounts }}
        - name: {{ .name }}
          configMap:
            name: {{ .configMap }}
      {{- end }}
      {{- range .Values.agent.extraSecretMounts }}
        - name: {{ .name }}
          secret:
            secretName: {{ .secretName }}
      {{- end }}
    {{- with .Values.agent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.agent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.agent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end -}}
