{{- if .Values.ydb.saPrivateKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jaeger-ydb-store.fullname" . }}
  labels:
    {{- include "jaeger-ydb-store.labels" . | nindent 4 }}
data:
  ydb-sa-key.pem: {{ .Values.ydb.saPrivateKey | b64enc }}
{{- end }}
